# This is a basic workflow to help you get started with Actions

name: test_environment_deploy_common
env:
  BUILD_SITE: more

# defines the reusable workflow
on:
  workflow_call:
    inputs:
      deploy_time:
        type: string
        description: Live Deploy Time
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "build" and another called "deploy_live" that deploys to the live environment
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Staging

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo The deploy job is complete!    
        
  deploy_live:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build
    environment: Live
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Start Live deploy
        run: |
          echo start deploy to live process,
          echo next wait for time selected: ${{ github.event.inputs.deploy_time }}.
          echo $(( $(date -f - +%s- <<< "today ${{ github.event.inputs.deploy_time }} MDT"$'\nnow') 0 ))
      - name: Wait until deploy time
        run: |
          sleep $(( $(date -f - +%s- <<< "today ${{ github.event.inputs.deploy_time }} MDT"$'\nnow') 0 ))
          echo deploy to live process,
          echo Time is up, please continue
      - name: Carry on with deploy
        run: |
          echo Carry on with the deploy to the live environment,
          echo the time is now.
